[package]
name = "code_to_ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-ap-rustc_lexer = "727.0.0"
rustc-ap-rustc_parse = "705.0.0"
const_fn = "0.4.9"